### ISSUE TITLE
allow to specify a season

### ISSUE THREAD

**Issue by tinker1234** [FishysPop/Mass-anime-downloader#1]
when i type demon slayer season 1 it brings up season 3
![image](https://github.com/FishysPop/Mass-anime-downloader/assets/30789433/fb2d38bd-49de-43a0-917c-e0b438212a03)

and as i was making the post the api went down

**Comment by FishysPop** [comment]
Not much i can do about the api going down but i will look into adding selectable search results since i dont control the search api

**Comment by FishysPop** [comment]
Added the ability to select the first 10 results, download the lastest version
